
image: node:10.15.0
definitions:
    caches:
        root-nm: ./node_modules
    cache-block: &caches
        - root-nm
    steps:
        - step: &lint
            name: Lint
            caches: *caches
            script:
                - yarn
                - yarn lint
        - step: &test
            name: Test
            caches: *caches
            script:
                - yarn
                - yarn test

pipelines:
    default:
        - step: *lint
        - parallel:
            - step: *test